### ISSUE TITLE
没找到模型下载路径

### ISSUE THREAD

**Issue by minmin0516** [AnitaSherry/search_by_Image#1]
python model_structure/modescope_init.py

**Comment by minmin0516** [comment]
code 中没找到这个文件在哪里

**Comment by AnitaSherry** [comment]
```
find / -type d -name "cv_resnest101_general_recognition" -print
```
服务器试试这个命令
如果是windows直接搜索cv_resnest101_general_recognition

**Comment by minmin0516** [comment]
更正一下 没有modescope_init.py这个python文件

**Comment by AnitaSherry** [comment]
抱歉，是我写错路径了，修改了[README.md](https://github.com/AnitaSherry/search_by_Image/blob/main/README.md)
下载模型使用
`python model/modescope_model_init.py`
