### ISSUE TITLE
请问，查询到的向量结果后，是如何返回的图片？

### ISSUE THREAD

**Issue by listento123** [AnitaSherry/search_by_Image#3]
请问作者，我们有没有额外建立一个数据库来存储原始图片呢？

**Comment by AnitaSherry** [comment]
> 请问作者，我们有没有额外建立一个数据库来存储原始图片呢？

1、存储图片向量同时存储了图片地址，通过这个地址返回图片
2、原始图片没有额外建立数据库，就存在一个文件夹中，可以额外简历数据库存储

**Comment by listento123** [comment]
感谢作者的回复
&nbsp;


无家可归的流浪狗
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月16日(星期三) 上午8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AnitaSherry/search_by_Image] 请问，查询到的向量结果后，是如何返回的图片？ (Issue #3)














  
请问作者，我们有没有额外建立一个数据库来存储原始图片呢？
  
1、存储图片向量同时存储了图片地址，通过这个地址返回图片
 2、原始图片没有额外建立数据库，就存在一个文件夹中，可以额外简历数据库存储
